    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="panel panel-custom">
                <div class="panel-heading">
                    <a id="logo" href="<?php echo BASE; ?>">
                        <img class="img-responsive" src="<?php echo IMG; ?>hxphp-logo.png" alt="">
                    </a> <br>
                    <?php echo (isset($this->menu) ? $this->menu : ''); ?>
                </div>
                <div class="panel-body">
                    <div class="alert alert-block alert-info">
                      <h4>Recupere sua senha.</h4>
                      Um link de redefinição será enviado para seu e-mail! Por favor verifique sua caixa de SPAM.
                    </div>
                    <form>
                      <div class="form-group">
                        <label for="email">E-mail</label>
                        <input type="email" name="email" class="form-control" id="email" placeholder="seuemail@site.com.br">
                      </div>
                      <button type="submit" class="btn btn-default">Enviar Link de Redefinição</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
